### ISSUE TITLE
2. Criar componentes do jogo

### ISSUE THREAD

**Issue by epreuss** [epreuss/visualnovel#2]

**Comment by GoingS** [comment]
- Um background (JLabel)
- Três sprites (JLabel)
- Uma caixa pro diálogo (JTextBox)

**Comment by epreuss** [comment]
Um Panel contendo um Botão 'Sim' e um Botão 'Não' para selecionar uma escolha. Também um Label mostrando um pequeno texto.

**Comment by epreuss** [comment]
Faz bem modularizado, colocando um Panel para cada grupo de componentes parecidos. 
Exemplo: Os sprites merecem ter seu Panel próprio. Fica bem mais fácil de arrastar os componentes e reorganizar eles quando precisar.
